import { PrismaClient, JobType, WorkplaceType, ExperienceLevel, JobStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🇩🇴 Cargando vacantes y empresas reales de República Dominicana...');

  // 1. Empresas Dominicanas Reconocidas
  const companiesData = [
    {
      name: 'Banco Popular Dominicano',
      slug: 'banco-popular-dominicano',
      rnc: '101010101',
      industry: 'Banca y Servicios Financieros',
      description: 'Líder del sistema financiero dominicano comprometido con el desarrollo económico y social del país.',
      logoUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=200&h=200&fit=crop',
      websiteUrl: 'https://www.popularenlinea.com',
      email: 'talento@bancopopular.com.do',
      province: 'Distrito Nacional',
      city: 'Santo Domingo',
      address: 'Torre Popular, Av. John F. Kennedy esq. Máximo Gómez',
      isVerified: true,
      jobs: [
        {
          title: 'Oficial de Atención al Cliente y Cajas',
          slug: 'oficial-de-atencion-al-cliente-y-cajas-santo-domingo',
          category: 'Servicio al Cliente',
          description: 'Responsable de brindar un servicio ágil, seguro y de excelencia a nuestros clientes en sucursales, procesando transacciones de depósito, retiro y asesoría de productos bancarios.',
          responsibilities: '• Gestionar transacciones de caja con estricto apego a normativas bancarias.\n• Asesorar a clientes sobre productos de ahorro, crédito y banca en línea.\n• Manejo de efectivo y cuadre diario de caja.',
          requirements: '• Estudiante universitario de Administración, Contabilidad, Economía o áreas afines.\n• 1 año de experiencia en servicio al cliente o manejo de valores.\n• Orientación al detalle, vocación de servicio y honestidad comprobada.',
          benefits: '• Salario competitivo + incentivos por desempeño.\n• Seguro médico complementario para ti y tu familia.\n• Beneficios bancarios exclusivos y tasa preferencial en préstamos.\n• Plan de carrera y formación continua en la Universidad Popular.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.ON_SITE,
          experienceLevel: ExperienceLevel.ENTRY,
          salaryMin: 32000,
          salaryMax: 42000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'Distrito Nacional',
          city: 'Santo Domingo',
          applyEmail: 'talento@bancopopular.com.do',
          featured: true,
          urgent: true,
          skills: ['Atención al Cliente', 'Manejo de Caja', 'Servicios Bancarios', 'Cuadre de Efectivo'],
        },
        {
          title: 'Analista de Seguridad Informática Jr.',
          slug: 'analista-de-seguridad-informatica-jr-distrito-nacional',
          category: 'Tecnología y Sistemas',
          description: 'Monitoreo preventivo y respuesta a incidentes en la infraestructura tecnológica del banco, protegiendo los datos de millones de cuentahabientes.',
          responsibilities: '• Monitorear alertas de seguridad y eventos en herramientas SIEM.\n• Colaborar en la revisión de políticas de contraseñas y accesos corporativos.\n• Ejecutar análisis básicos de vulnerabilidades en sistemas internos.',
          requirements: '• Graduado o estudiante de término de Ingeniería en Sistemas, Telemática o Ciberseguridad.\n• Conocimientos en redes TCP/IP, cortafuegos y sistemas operativos Windows/Linux.\n• Deseable certificación CompTIA Security+ o equivalente.',
          benefits: '• Plan de salud de cobertura amplia.\n• Modalidad de trabajo híbrida (3 días presencial / 2 días remoto).\n• Bono anual por metas institucionales.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.HYBRID,
          experienceLevel: ExperienceLevel.MID,
          salaryMin: 55000,
          salaryMax: 75000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'Distrito Nacional',
          city: 'Santo Domingo',
          applyEmail: 'seguridad-talento@bancopopular.com.do',
          featured: false,
          urgent: false,
          skills: ['Ciberseguridad', 'SIEM', 'Linux', 'Redes', 'Análisis de Vulnerabilidades'],
        },
      ],
    },
    {
      name: 'Centro Cuesta Nacional (CCN)',
      slug: 'centro-cuesta-nacional-ccn',
      rnc: '101002345',
      industry: 'Comercio y Retail',
      description: 'Líder en venta al detalle en República Dominicana a través de sus reconocidas marcas Supermercados Nacional, Jumbo, Casa Cuesta, Juguetón y Bebemundo.',
      logoUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=200&h=200&fit=crop',
      websiteUrl: 'https://ccn.net.do',
      email: 'empleos@ccn.net.do',
      province: 'Distrito Nacional',
      city: 'Santo Domingo',
      address: 'Av. Luperón esq. Gustavo Mejía Ricart',
      isVerified: true,
      jobs: [
        {
          title: 'Auxiliar de Tienda y Servicio al Cliente (Jumbo)',
          slug: 'auxiliar-de-tienda-y-servicio-al-cliente-jumbo-santiago',
          category: 'Ventas y Comercio',
          description: 'Atención a visitantes, reposición ordenada de mercancías en pasillos y asistencia a clientes en la tienda Jumbo de Santiago.',
          responsibilities: '• Asistir cordialmente a los clientes con información de precios y pasillos.\n• Rotación de productos bajo el principio FIFO (primeras entradas, primeras salidas).\n• Mantener góndolas limpias y debidamente etiquetadas.',
          requirements: '• Bachiller graduado (indispensable).\n• Disponibilidad para laborar en turnos rotativos.\n• Buenas relaciones interpersonales y dinamismo.',
          benefits: '• Sueldo fijo con pago puntual quincenal.\n• Seguro médico y cooperativa de empleados con ahorros y préstamos.\n• Descuentos especiales en compras en todas las tiendas del grupo CCN.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.ON_SITE,
          experienceLevel: ExperienceLevel.ENTRY,
          salaryMin: 28000,
          salaryMax: 35000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'Santiago',
          city: 'Santiago de los Caballeros',
          applyEmail: 'empleos@ccn.net.do',
          featured: true,
          urgent: true,
          skills: ['Servicio al Cliente', 'Reposición de Mercancía', 'Trabajo en Equipo', 'Ventas Retail'],
        },
        {
          title: 'Supervisor de Almacén y Control de Inventarios',
          slug: 'supervisor-de-almacen-y-control-de-inventarios-santo-domingo',
          category: 'Logística y Almacén',
          description: 'Supervisión de recepción, despacho y almacenamiento de mercancía seca y refrigerada en nuestro Centro de Distribución.',
          responsibilities: '• Coordinar al equipo de montacarguistas y estibadores.\n• Auditorías de inventario cíclico y reporte de mermas.\n• Asegurar el cumplimiento de normas de seguridad industrial y salud ocupacional.',
          requirements: '• Tecnólogo o Licenciatura en Logística, Ingeniería Industrial o afines.\n• 2 años de experiencia en centros de distribución o almacenes de gran escala.\n• Manejo intermedio de Excel y sistemas WMS o SAP.',
          benefits: '• Salario competitivo + horas extras remuneradas.\n• Almuerzo subsidiado en comedor corporativo.\n• Transporte en rutas establecidas.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.ON_SITE,
          experienceLevel: ExperienceLevel.MID,
          salaryMin: 45000,
          salaryMax: 60000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'Santo Domingo',
          city: 'Santo Domingo Oeste',
          applyEmail: 'logistica-talento@ccn.net.do',
          featured: false,
          urgent: false,
          skills: ['Inventarios', 'Logística', 'SAP WMS', 'Supervisión de Personal', 'Excel'],
        },
      ],
    },
    {
      name: 'Teleperformance República Dominicana',
      slug: 'teleperformance-rd',
      rnc: '130987654',
      industry: 'Call Center y BPO',
      description: 'Líder mundial en servicios digitales integrados y gestión de experiencia de cliente con centros de operaciones en Santo Domingo y miles de agentes remotos en todo el país.',
      logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=200&h=200&fit=crop',
      websiteUrl: 'https://www.teleperformance.com',
      email: 'recruitment.dr@teleperformance.com',
      province: 'Distrito Nacional',
      city: 'Santo Domingo',
      address: 'Av. 27 de Febrero esq. Tiradentes',
      isVerified: true,
      jobs: [
        {
          title: 'Bilingual Customer Service Specialist (Work from Home RD)',
          slug: 'bilingual-customer-service-specialist-work-from-home-rd',
          category: 'Call Center y BPO',
          description: 'Provide top-tier inbound customer support for major international e-commerce and retail brands. 100% remote position anywhere in the Dominican Republic with provided computer equipment.',
          responsibilities: '• Answer inbound calls and inquiries from English-speaking customers.\n• Assist with orders, refunds, product inquiries, and account updates.\n• Maintain high customer satisfaction ratings (CSAT).',
          requirements: '• Advanced English proficiency (B2+ or C1 level, fluent conversational skills).\n• High School diploma completed.\n• Reliable home internet connection (fiber optic preferred).\n• Residing in the Dominican Republic.',
          benefits: '• Base salary + monthly performance bonuses in USD/DOP.\n• Complete computer equipment provided and delivered to your home.\n• Medical insurance plan.\n• Paid training from day one.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.REMOTE,
          experienceLevel: ExperienceLevel.ENTRY,
          salaryMin: 48000,
          salaryMax: 70000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'Distrito Nacional',
          city: 'Santo Domingo',
          applyEmail: 'recruitment.dr@teleperformance.com',
          featured: true,
          urgent: true,
          skills: ['English B2/C1', 'Customer Service', 'Problem Solving', 'Computer Skills'],
        },
        {
          title: 'Technical Support Representative - English/Spanish',
          slug: 'technical-support-representative-english-spanish-santo-domingo',
          category: 'Call Center y BPO',
          description: 'Diagnosticar y resolver incidencias técnicas de hardware, software y conectividad para usuarios corporativos en Norteamérica.',
          responsibilities: '• Guiar a los usuarios paso a paso en configuración de cuentas y resolución de problemas técnicos.\n• Documentar casos en sistemas de ticketing (Zendesk / Jira).\n• Escalar casos críticos al equipo de ingeniería.',
          requirements: '• Dominio fluido del inglés (oral y escrito mínimo 80%).\n• Pasión por la tecnología y conocimientos básicos en redes o soporte técnico.\n• Buenas habilidades de comunicación.',
          benefits: '• Salario base + incentivos de productividad.\n• Transporte corporativo nocturno puerta a puerta.\n• Oportunidades de ascenso a Team Leader o QA en menos de un año.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.ON_SITE,
          experienceLevel: ExperienceLevel.MID,
          salaryMin: 52000,
          salaryMax: 68000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'Distrito Nacional',
          city: 'Santo Domingo',
          applyEmail: 'recruitment.dr@teleperformance.com',
          featured: false,
          urgent: false,
          skills: ['Inglés Fluido', 'Soporte Técnico', 'Ticketing', 'Troubleshooting', 'Customer Care'],
        },
      ],
    },
    {
      name: 'Grupo Ramos (Sirena & Aprezio)',
      slug: 'grupo-ramos',
      rnc: '101000123',
      industry: 'Comercio y Retail',
      description: 'Una de las principales empresas empleadoras privadas de República Dominicana, operando los hipermercados Sirena, Sirena Market, Aprezio y centros comerciales Multiplaza.',
      logoUrl: 'https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=200&h=200&fit=crop',
      websiteUrl: 'https://gruporamos.com',
      email: 'empleos@gruporamos.com',
      province: 'Distrito Nacional',
      city: 'Santo Domingo',
      address: 'Av. Winston Churchill esq. Ángel Severo Cabral',
      isVerified: true,
      jobs: [
        {
          title: 'Cajero(a) Comercial - Sirena San Cristóbal',
          slug: 'cajero-comercial-sirena-san-cristobal',
          category: 'Ventas y Comercio',
          description: 'Atención en terminales de punto de venta (POS), cobro ágil y seguro de mercancías y orientación a clientes.',
          responsibilities: '• Facturar compras utilizando lectores de códigos de barra y sistemas POS.\n• Manejo de pagos en efectivo, tarjetas de crédito, débito y bonos.\n• Brindar un trato afable y cordial a cada comprador.',
          requirements: '• Bachiller concluido.\n• Experiencia previa en manejo de cajas (deseable pero no obligatoria, se ofrece inducción).\n• Residir en San Cristóbal o zonas aledañas.',
          benefits: '• Salario conforme a ley + bonificación anual garantizada.\n• Beneficios de ley: seguro familiar de salud y fondo de pensiones.\n• Descuentos corporativos para compras del hogar.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.ON_SITE,
          experienceLevel: ExperienceLevel.ENTRY,
          salaryMin: 27000,
          salaryMax: 33000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'San Cristóbal',
          city: 'San Cristóbal',
          applyEmail: 'empleos@gruporamos.com',
          featured: false,
          urgent: true,
          skills: ['Caja Registradora', 'Cobros', 'Atención al Cliente', 'Responsabilidad'],
        },
      ],
    },
    {
      name: 'Puntacana Resort & Club',
      slug: 'puntacana-resort-and-club',
      rnc: '101054321',
      industry: 'Hotelería y Turismo',
      description: 'Pioneros del desarrollo turístico sostenible en la región este de República Dominicana, operando complejos hoteleros de lujo y el Aeropuerto Internacional de Punta Cana.',
      logoUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=200&h=200&fit=crop',
      websiteUrl: 'https://www.puntacana.com',
      email: 'talento@puntacana.com',
      province: 'La Altagracia (Punta Cana / Bávaro)',
      city: 'Punta Cana',
      address: 'Punta Cana Resort, Carretera Aeropuerto',
      isVerified: true,
      jobs: [
        {
          title: 'Recepcionista Bilingüe de Hotel de Lujo',
          slug: 'recepcionista-bilingue-hotel-lujo-punta-cana',
          category: 'Hotelería y Turismo',
          description: 'Gestión de check-in, check-out y atención personalizada a huéspedes internacionales en exclusivo hotel 5 estrellas.',
          responsibilities: '• Recibir cordialmente a huéspedes y gestionar reservaciones en sistema hotelero.\n• Asistir en solicitudes de concierge, transporte y amenidades.\n• Facturación de consumos y cobro de estancias.',
          requirements: '• Grado o técnico en Hotelería, Turismo, Lenguas Modernas o afines.\n• Dominio avanzado del inglés (se valora un segundo idioma como francés o ruso).\n• Excelente presencia y vocación por la hospitalidad.',
          benefits: '• Salario atractivo + propina legal del 10% distribuida mensualmente.\n• Alojamiento corporativo o subsidio de vivienda en la zona este.\n• Alimentación en el hotel durante turnos laborales.\n• Seguro médico privado.',
          jobType: JobType.FULL_TIME,
          workplaceType: WorkplaceType.ON_SITE,
          experienceLevel: ExperienceLevel.MID,
          salaryMin: 40000,
          salaryMax: 65000,
          salaryCurrency: 'DOP',
          salaryPeriod: 'MONTHLY',
          isSalaryPublic: true,
          province: 'La Altagracia (Punta Cana / Bávaro)',
          city: 'Punta Cana',
          applyEmail: 'talento@puntacana.com',
          featured: true,
          urgent: false,
          skills: ['Inglés Avanzado', 'Hospitalidad', 'Sistemas Hoteleros', 'Check-in/Check-out', 'Servicio VIP'],
        },
      ],
    },
  ];

  for (const comp of companiesData) {
    // Upsert empresa
    const company = await prisma.company.upsert({
      where: { slug: comp.slug },
      update: {
        name: comp.name,
        rnc: comp.rnc,
        industry: comp.industry,
        description: comp.description,
        logoUrl: comp.logoUrl,
        websiteUrl: comp.websiteUrl,
        email: comp.email,
        province: comp.province,
        city: comp.city,
        address: comp.address,
        isVerified: comp.isVerified,
      },
      create: {
        name: comp.name,
        slug: comp.slug,
        rnc: comp.rnc,
        industry: comp.industry,
        description: comp.description,
        logoUrl: comp.logoUrl,
        websiteUrl: comp.websiteUrl,
        email: comp.email,
        province: comp.province,
        city: comp.city,
        address: comp.address,
        isVerified: comp.isVerified,
      },
    });

    console.log(`🏢 Empresa sincronizada: ${company.name}`);

    for (const j of comp.jobs) {
      const existingJob = await prisma.job.findUnique({ where: { slug: j.slug } });
      if (!existingJob) {
        await prisma.job.create({
          data: {
            companyId: company.id,
            title: j.title,
            slug: j.slug,
            category: j.category,
            description: j.description,
            responsibilities: j.responsibilities,
            requirements: j.requirements,
            benefits: j.benefits,
            jobType: j.jobType,
            workplaceType: j.workplaceType,
            experienceLevel: j.experienceLevel,
            salaryMin: j.salaryMin,
            salaryMax: j.salaryMax,
            salaryCurrency: j.salaryCurrency,
            salaryPeriod: j.salaryPeriod,
            isSalaryPublic: j.isSalaryPublic,
            province: j.province,
            city: j.city,
            applyEmail: j.applyEmail,
            status: JobStatus.PUBLISHED,
            featured: j.featured,
            urgent: j.urgent,
            skills: {
              create: j.skills.map((s) => ({ skillName: s })),
            },
          },
        });
        console.log(`  💼 Vacante creada: ${j.title} (${j.province})`);
      } else {
        console.log(`  ℹ️ Vacante ya existente: ${j.title}`);
      }
    }
  }

  const finalCount = await prisma.job.count({ where: { status: JobStatus.PUBLISHED } });
  console.log(`\n🎉 Proceso finalizado con éxito! Total de vacantes activas en DB: ${finalCount}`);
}

main()
  .catch((e) => {
    console.error('Error en seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
